/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pigliavento;







import Pigliavento.db.ConnectionProvider;

import Pigliavento.model.Actions;
import Pigliavento.model.ActionsImpl;
import Pigliavento.view.View;

public class App {
    public static void main(String[] args) {
        final ConnectionProvider connectionProvider = new ConnectionProvider("root", "POLIsucco75!", "Pigliavento");
        final Actions actions = new ActionsImpl(connectionProvider.getMySQLConnection());
        new View(actions);
    }
}
